# Configuration file for Bitbucket Pipelines that enables continuous delivery for this project.

image: hashicorp/terraform:1.1.5

pipelines:
    default:
      - step:
          name: Build and deploy
          services:
            - docker
          script:
            - export VERSION=$BITBUCKET_BUILD_NUMBER
            -  chmod +x ./deploy.sh
            - ./deploy.sh
